### PR TITLE
Updated the TODO. Explained the Values

### PR DESCRIPTION
**Pull request by Mechtecs**
Its a simple Two Arrow Draw.

### CODE REVIEW

**Comment by lawrancej** [comment]
Thanks for the PR! I'll take a look at it shortly.

**Comment by Mechtecs** [comment]
Is there a chance to gest Write Access?? Because i want to work on the todo list :)

**Comment by lawrancej** [comment]
I'm happy to merge in your changes. I prefer the distributed workflow over a centralized repo.

**Comment by Mechtecs** [comment]
mkay :) +1

**Comment by lawrancej** [comment]
Awesome! Thank you!

**Pull request merged**
